name: platform_adaptive_widgets
description: "A new Flutter package project."
version: 0.0.0
homepage:






environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0 <4.0.0"






dependencies:
  flutter:
    sdk: flutter






dev_dependencies:
  flutter_test:
    sdk: flutter
  # Analysis
  # dart_code_metrics:metrics check-unused-files lib --disable-sunset-warning
  # dependency_validator
  # Selectively on/off due to https://github.com/huanghui1998hhh/prefer_shorthands/issues/7
#  prefer_shorthands: ^0.4.7
