name: platform_adaptive_widgets
description: "A spiritual continuation of flutter_platform_widgets library"
version: 1.0.1
homepage: https://github.com/LahaLuhem/platform_adaptive_widgets?tab=readme-ov-file
repository: https://github.com/LahaLuhem/platform_adaptive_widgets

platforms:
  android:
  ios:

topics:
  - adaptive
  - widget
  - material-design
  - material3
  - cupertino






environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"






dependencies:
  flutter:
    sdk: flutter
  material_ui: ^0.0.1
  cupertino_ui: ^0.0.1
  pull_down_button: ^0.10.2






dev_dependencies:
  flutter_test:
    sdk: flutter
  # Analysis
  # dart_code_metrics:metrics check-unused-files lib --disable-sunset-warning
  # dependency_validator
  # Selectively on/off due to https://github.com/huanghui1998hhh/prefer_shorthands/issues/7
#  prefer_shorthands: ^0.4.7
